-- Migration 0009: super_products
-- Catálogo de /super: la lista real de recomendaciones de Hugo, extraída
-- de su deck [RECOMENDACION DE ALIMENTOS 2.4]. Las notas (note) las va
-- llenando Hugo desde el admin. amazon_url solo donde su deck ya tenía
-- link (limpiado de tags de afiliado ajenos; el tag propio se agrega
-- cuando Hugo tenga su cuenta de Afiliados).

CREATE TABLE IF NOT EXISTS super_products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT,
  category TEXT NOT NULL,
  image TEXT NOT NULL,
  note TEXT,
  amazon_url TEXT,
  clicks INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active',
  sort INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_super_cat ON super_products(category, status, sort);

INSERT OR IGNORE INTO super_products (id, name, brand, category, image, note, amazon_url, status, sort) VALUES
('tortireglas-delgaditas','Tortillas Delgaditas 3=1','Tortiregias','cereales','/assets/super/tortireglas-delgaditas.png',NULL,NULL,'active',0),
('saralee-delightful-multigrano','Pan Delightful Multigrano 45','Sara Lee','cereales','/assets/super/saralee-delightful-multigrano.png',NULL,NULL,'active',1),
('saralee-delightful-integral','Pan Delightful 100% Integral 45','Sara Lee','cereales','/assets/super/saralee-delightful-integral.png',NULL,NULL,'active',2),
('sanissimo-salmas-caja','Salmas horneadas (caja)','Sanissimo','cereales','/assets/super/sanissimo-salmas-caja.png',NULL,NULL,'active',3),
('lamoderna-spaghetti-integral','Spaghetti Integral','La Moderna','cereales','/assets/super/lamoderna-spaghetti-integral.png',NULL,NULL,'active',4),
('verdevalle-arroz-integral','Arroz Integral','Verde Valle','cereales','/assets/super/verdevalle-arroz-integral.png',NULL,NULL,'active',5),
('sabanitas-fibrelas','Tortillas Sabanitas 4=1 Fibrelas','Sabanitas','cereales','/assets/super/sabanitas-fibrelas.png',NULL,NULL,'active',6),
('thins-multigrano','Thins Multigrano 94 kcal','Bimbo','cereales','/assets/super/thins-multigrano.png',NULL,NULL,'active',7),
('bimbo-cero-cero','Pan Cero Cero Multigrano','Bimbo','cereales','/assets/super/bimbo-cero-cero.png',NULL,NULL,'active',8),
('ezekiel-tortillas','Tortillas de granos germinados Ezekiel 4:9','Food for Life','cereales','/assets/super/ezekiel-tortillas.png',NULL,NULL,'active',9),
('ezekiel-pan','Pan de granos germinados Ezekiel 4:9','Food for Life','cereales','/assets/super/ezekiel-pan.png',NULL,NULL,'active',10),
('susalia-tostadas','Tostadas horneadas maíz-nopal','Susalia','cereales','/assets/super/susalia-tostadas.png',NULL,NULL,'active',11),
('tortireglas-tostadas','Tostadas Delgaditas 3=1','Tortiregias','cereales','/assets/super/tortireglas-tostadas.png',NULL,NULL,'active',12),
('sanissimo-salmas-bolsa','Salmas horneadas (bolsa)','Sanissimo','cereales','/assets/super/sanissimo-salmas-bolsa.png',NULL,NULL,'active',13),
('gerber-arroz','Cereal de arroz','Gerber','cereales','/assets/super/gerber-arroz.png',NULL,NULL,'active',14),
('granola-artesanal','Granola artesanal 100% natural',NULL,'cereales','/assets/super/granola-artesanal.png',NULL,NULL,'active',15),
('okko-rice-cakes','Rice Cakes con quinoa','OKKO','cereales','/assets/super/okko-rice-cakes.png',NULL,NULL,'active',16),
('slimpop-palomitas','Palomitas Sal de Mar','Slim Pop','cereales','/assets/super/slimpop-palomitas.png',NULL,NULL,'active',17),
('bachoco-pechuga','Pechuga fresca de granja','Bachoco','proteinas','/assets/super/bachoco-pechuga.png',NULL,NULL,'active',18),
('dolores-medallones','Medallones de Atún Premium','Dolores','proteinas','/assets/super/dolores-medallones.png',NULL,NULL,'active',19),
('dolores-cubitos','Cubitos de Atún','Dolores','proteinas','/assets/super/dolores-cubitos.png',NULL,NULL,'active',20),
('marina-azul-atun','Atún en agua (pouch)','Marina Azul','proteinas','/assets/super/marina-azul-atun.png',NULL,NULL,'active',21),
('dolores-lomo-solido','Lomo Sólido de Atún en Agua','Dolores','proteinas','/assets/super/dolores-lomo-solido.png',NULL,NULL,'active',22),
('sierra-madre-tilapia','Filete Blanco del Nilo 1 kg','Sierra Madre','proteinas','/assets/super/sierra-madre-tilapia.png',NULL,NULL,'active',23),
('san-rafael-pavo','Pechuga de Pavo Balance','San Rafael','proteinas','/assets/super/san-rafael-pavo.png',NULL,NULL,'active',24),
('heb-queso-panela','Queso Panela deslactosado','HEB','proteinas','/assets/super/heb-queso-panela.png',NULL,NULL,'active',25),
('heb-tilapia','Filete de tilapia congelado','HEB','proteinas','/assets/super/heb-tilapia.png',NULL,NULL,'active',26),
('dolores-atun-fresco','Atún fresco (charola)','Dolores','proteinas','/assets/super/dolores-atun-fresco.png',NULL,NULL,'active',27),
('san-juan-claras','Claras de Huevo 1 kg','San Juan','proteinas','/assets/super/san-juan-claras.png',NULL,NULL,'active',28),
('heb-carne-molida','Carne molida de res Supreme','HEB','proteinas','/assets/super/heb-carne-molida.png',NULL,NULL,'active',29),
('tio-lencho-carne-seca','Carne Seca de Res','Tío Lencho','proteinas','/assets/super/tio-lencho-carne-seca.png',NULL,NULL,'active',30),
('kirkland-pavo','Pechuga de Pavo asada al horno','Kirkland','proteinas','/assets/super/kirkland-pavo.png',NULL,NULL,'active',31),
('pam-oliva','Spray antiadherente Oliva','PAM','grasas','/assets/super/pam-oliva.png',NULL,NULL,'active',32),
('pam-coco','Spray antiadherente Coconut Oil','PAM','grasas','/assets/super/pam-coco.png',NULL,NULL,'active',33),
('tutipo-ghee','Ghee mantequilla clarificada','Tu Tipo','grasas','/assets/super/tutipo-ghee.png',NULL,NULL,'active',34),
('gloria-mantequilla','Mantequilla pura de vaca sin sal','Gloria','grasas','/assets/super/gloria-mantequilla.png',NULL,NULL,'active',35),
('heb-aceite-aguacate','Aceite de Aguacate','HEB','grasas','/assets/super/heb-aceite-aguacate.png',NULL,NULL,'active',36),
('heb-aceite-oliva','Aceite puro de Oliva','HEB','grasas','/assets/super/heb-aceite-oliva.png',NULL,NULL,'active',37),
('heb-aceite-coco','Aceite de Coco extra virgen Organics','HEB','grasas','/assets/super/heb-aceite-coco.png',NULL,NULL,'active',38),
('lala100-proteina','Lala 100 sin lactosa 54 g proteína','Lala','lacteos','/assets/super/lala100-proteina.png',NULL,NULL,'active',39),
('heb-yogurt-griego','Yogurt Greek Plain 0%','HEB','lacteos','/assets/super/heb-yogurt-griego.png',NULL,NULL,'active',40),
('heb-almond-milk','Almond Milk vainilla sin endulzar','HEB','lacteos','/assets/super/heb-almond-milk.png',NULL,NULL,'active',41),
('chobani-20g','Yogurt 20 g Protein Zero Added Sugar','Chobani','lacteos','/assets/super/chobani-20g.png',NULL,NULL,'active',42),
('chobani-complete','Chobani Complete 14 g proteína','Chobani','lacteos','/assets/super/chobani-complete.png',NULL,NULL,'active',43),
('chobani-zero','Yogurt Zero Sugar Vanilla','Chobani','lacteos','/assets/super/chobani-zero.png',NULL,NULL,'active',44),
('dontworry-merengues','Merengues Light 1 caloría','don''t worry','libres','/assets/super/dontworry-merengues.png',NULL,NULL,'active',45),
('pronto-light-gelatina','Gelatina Light 0% azúcar','Pronto','libres','/assets/super/pronto-light-gelatina.png',NULL,NULL,'active',46),
('infusionate-jamaica','Flor de Jamaica con Stevia','Infusiónate','libres','/assets/super/infusionate-jamaica.png',NULL,NULL,'active',47),
('njoy-stevia','Stevia molida 100% natural','N''Joy','libres','/assets/super/njoy-stevia.png',NULL,NULL,'active',48),
('topo-chico','Agua mineral','Topo Chico','libres','/assets/super/topo-chico.png',NULL,NULL,'active',49),
('chilakia-molcajete','Salsa casera La Molcajete','Chilakia','libres','/assets/super/chilakia-molcajete.png',NULL,NULL,'active',50),
('novoxal-sal','Sal yodada reducida en sodio Light','Novoxal','libres','/assets/super/novoxal-sal.png',NULL,NULL,'active',51),
('sazonador','Sazonador de especias',NULL,'libres','/assets/super/sazonador.png',NULL,NULL,'active',52),
('fiberone-brownies','Brownies 70 calorías','Fiber One','libres','/assets/super/fiberone-brownies.png',NULL,NULL,'active',53),
('susalia-susalitas','Susalitas Flama horneadas','Susalia','libres','/assets/super/susalia-susalitas.png',NULL,NULL,'active',54),
('amaeca-tortillas','Tortillas de amaranto','Amaeca','libres','/assets/super/amaeca-tortillas.png',NULL,NULL,'active',55),
('belight-bebida','Bebida Be Light','Be Light','libres','/assets/super/belight-bebida.png',NULL,NULL,'active',56),
('bebida-viva-kombucha','Kombucha Bebida Viva','Bebida Viva','libres','/assets/super/bebida-viva-kombucha.png',NULL,NULL,'active',57),
('gat-caffeine','Caffeine','GAT Sport','suplementos','/assets/super/gat-caffeine.png',NULL,'https://www.amazon.com.mx/dp/B01MSU5LM1','active',58),
('dymatize-iso100','ISO100 Hydrolyzed','Dymatize','suplementos','/assets/super/dymatize-iso100.png',NULL,NULL,'active',59),
('isopure-zero','Isopure Zero Carb','Isopure','suplementos','/assets/super/isopure-zero.png',NULL,NULL,'active',60),
('gat-beta-alanina','Beta-Alanine','GAT Sport','suplementos','/assets/super/gat-beta-alanina.png',NULL,'https://www.amazon.com.mx/dp/B07NY3PLLZ','active',61),
('now-lysine','L-Lysine 1000 mg','NOW Foods','suplementos','/assets/super/now-lysine.png',NULL,'https://www.amazon.com.mx/dp/B000Z9361G','active',62),
('now-d3k2','Vitamina D-3 & K-2','NOW Foods','suplementos','/assets/super/now-d3k2.png',NULL,NULL,'active',63),
('now-magnesio','Magnesium Glycinate','NOW Foods','suplementos','/assets/super/now-magnesio.png',NULL,'https://www.amazon.com.mx/dp/B07NWMVMT1','active',64),
('metamucil','Fibra natural en polvo','Metamucil','suplementos','/assets/super/metamucil.png',NULL,'https://www.amazon.com.mx/dp/B074SZ6D3P','active',65),
('lysi-omega3','Omega-3 Forte','Lýsi','suplementos','/assets/super/lysi-omega3.png',NULL,'https://www.amazon.com.mx/dp/B0CQMZ4HW6','active',66),
('now-carnitina','L-Carnitine 1000 mg','NOW Foods','suplementos','/assets/super/now-carnitina.png',NULL,'https://www.amazon.com.mx/dp/B001B4NDF8','active',67),
('kirkland-barras','Barras de proteína','Kirkland','suplementos','/assets/super/kirkland-barras.png',NULL,'https://www.amazon.com.mx/dp/B09LCLBJ2Z','active',68),
('now-ginseng','Panax Ginseng','NOW Foods','suplementos','/assets/super/now-ginseng.png',NULL,'https://www.amazon.com.mx/dp/B005P0KF32','active',69),
('easyfit-lata','Proteína Easyfit (lata)','Easyfit','suplementos','/assets/super/easyfit-lata.png',NULL,NULL,'active',70),
('habits-cacao','Proteína High Performance Cacao','HABITS','suplementos','/assets/super/habits-cacao.png',NULL,'https://www.amazon.com.mx/dp/B0BLY18C7M','active',71),
('birdman-creatina','Creatina Monohidratada','Birdman','suplementos','/assets/super/birdman-creatina.png',NULL,NULL,'active',72),
('blife-joint','Joint Blend','B Life','suplementos','/assets/super/blife-joint.png',NULL,'https://www.amazon.com.mx/dp/B07X9J5S53','active',73),
('easyfit-sobre','Proteína Easyfit (sobres)','Easyfit','suplementos','/assets/super/easyfit-sobre.png',NULL,'https://www.amazon.com.mx/dp/B0DX8J8NPL','active',74),
('habits-sobre','Proteína HABITS (sobre)','HABITS','suplementos','/assets/super/habits-sobre.png',NULL,'https://www.amazon.com.mx/dp/B0CQJMX55P','active',75),
('turin-sin-azucar','Chocolate amargo sin azúcar','Turín','oxxo','/assets/super/turin-sin-azucar.png',NULL,NULL,'active',76),
('larin-cero','Chocolate Larín Cero','Nestlé','oxxo','/assets/super/larin-cero.png',NULL,NULL,'active',77),
('carlosv-sin-azucar','Carlos V sin azúcar','Nestlé','oxxo','/assets/super/carlosv-sin-azucar.png',NULL,NULL,'active',78),
('bokados-cacahuates','Cacahuates fritos con sal','Bokados','oxxo','/assets/super/bokados-cacahuates.png',NULL,NULL,'active',79),
('sabritas-chicharron','Chicharrón de cerdo 0 g grasas trans','Sabritas','oxxo','/assets/super/sabritas-chicharron.png',NULL,NULL,'active',80),
('botanita-carnisnack','Carnisnack tiras de carne seca','Botanita','oxxo','/assets/super/botanita-carnisnack.png',NULL,NULL,'active',81),
('dany-gelatina','Gelatina Dany','Danone','oxxo','/assets/super/dany-gelatina.png',NULL,NULL,'active',82),
('4buddies-palomitas','Palomitas de maíz (varios sabores)','4Buddies','oxxo','/assets/super/4buddies-palomitas.png',NULL,NULL,'active',83),
('yoplait-griego','Yogurt Griego sin azúcar añadida','Yoplait','oxxo','/assets/super/yoplait-griego.png',NULL,NULL,'active',84),
('natures-heart-nutty','Nutty Berry Mix','Nature''s Heart','oxxo','/assets/super/natures-heart-nutty.png',NULL,NULL,'active',85),
('lala100-shake','Lala 100 shake 15 g proteína cacao','Lala','oxxo','/assets/super/lala100-shake.png',NULL,NULL,'active',86),
('berry-nuts','Berry Nuts mezclas con granola','Berry Nuts','oxxo','/assets/super/berry-nuts.png',NULL,NULL,'active',87),
('bascula-cocina','Báscula digital de cocina',NULL,'material','/assets/super/bascula-cocina.png',NULL,'https://www.amazon.com.mx/dp/B0BV2XH34J','active',88),
('tazas-medidoras','Set de tazas y cucharas medidoras',NULL,'material','/assets/super/tazas-medidoras.png',NULL,'https://www.amazon.com.mx/dp/B0B6399YF2','active',89),
('contenedores','Contenedores para meal prep',NULL,'material','/assets/super/contenedores.png',NULL,'https://www.amazon.com.mx/dp/B0BFDX7TJ2','active',90),
('lonchera','Lonchera térmica',NULL,'material','/assets/super/lonchera.png',NULL,'https://www.amazon.com.mx/dp/B0B3JF81M1','active',91);
